### PR TITLE
Try to fallback to CNI gateway when regular address fails.

### LINKED ISSUE #1573: Podman support for interactive mode
In Earthly 0.6 interactive mode does not work with podman
```
earthly -i +build

 1. Init 🚀
————————————————————————————————————————————————————————————————————————————————

           buildkitd | Found buildkit daemon as podman container (earthly-buildkitd)


 2. Build 🔧
————————————————————————————————————————————————————————————————————————————————

         alpine:3.13 | --> Load metadata linux/amd64
               +base | --> FROM alpine:3.13
               +base | [██████████] 100% resolve docker.io/library/alpine:3.13@sha256:026f721af4cf2843e07bba648e158fb35ecc876d822130633cc49f707f0fc88c
               +base | [██████████] 100% sha256:5758d4e389a3f662e94a85fb76143dbe338b64f8d2a65f45536a9663b05305ad
               +base | [██████████] 100% extracting sha256:5758d4e389a3f662e94a85fb76143dbe338b64f8d2a65f45536a9663b05305ad
               +base | --> WORKDIR /test
              +build | --> RUN false
              +build | Entering interactive debugger (**Warning: only a single debugger per host is supported**)
              +build | Command /bin/sh -c false failed with exit code 1
              +build | time="2022-01-13T07:36:18Z" level=error msg="failed to connect to remote debugger: dial tcp :8373: connect: connection refused"
              +build | ERROR: Command exited with non-zero code: RUN false

============================ ❌ FAILURE [2. Build 🔧] ============================

Repeating the output of the command that caused the failure
              +build *failed* | --> RUN false
              +build *failed* | Entering interactive debugger (**Warning: only a single debugger per host is supported**)
              +build *failed* | Command /bin/sh -c false failed with exit code 1
              +build *failed* | time="2022-01-13T07:36:18Z" level=error msg="failed to connect to remote debugger: dial tcp :8373: connect: connection refused"
              +build *failed* | ERROR: Command exited with non-zero code: RUN false
Error: build target: build main: bkClient.Build: failed to solve: process "/bin/sh -c PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin /usr/bin/earth_debugger /bin/sh -c 'false'" did not complete successfully: exit code: 1
```

See slack thread here:
https://earthlycommunity.slack.com/archives/C01DL2928RM/p1642059778043000

### PR DESCRIPTION
**Pull request by dchw**
According to the CNI spec, our `host-local` ipam module will always put the gateway at `.1` inside our subnet. If the derived address from the config fails to connect, fallback and try the internal CNI gateway. Should improve compatibility when the container does not have an IP, such as rootless configurations.

Fixes #1573.

### CODE REVIEW

File: cmd/debugger/main.go [hunk 1]
```diff
@@ -89,7 +91,15 @@ func interactiveMode(ctx context.Context, remoteConsoleAddr string, cmdBuilder f
...
-		return errors.Wrap(err, "failed to connect to remote debugger")
+		// If the IP we derived at start fails, try the reserved gateway address for our internal CNI network.
+		// The CIDR range for this can be found in buildkitd/cni-conf.json.template, so if that ever changes, we need to change it here, too.
+		// Relevant CNI docs for the host-local ipam module: https://www.cni.dev/plugins/current/ipam/host-local/
+		// tl;dr we can assume the gateway is at .1 in the subnet.
+		log.Debug(fmt.Sprintf("Failed to connect to \"%s\", trying internal CNI fallback \"%s\".", remoteConsoleAddr, cniFallbackHost))
+		conn, err = net.Dial("tcp", cniFallbackHost)
+		if err != nil {
+			return errors.Wrap(err, "failed to connect to remote debugger")
+		}
```
Comment (vladaionescu) [inline cmd/debugger/main.go:102]: Could we switch completely to the CNI one only? We'd be able to get rid of the port assignment on the host.

Or at the very least, try the CNI one address first, and if that doesn't work, try the old one.

File: cmd/debugger/main.go [hunk 2]
```diff
@@ -89,7 +91,15 @@ func interactiveMode(ctx context.Context, remoteConsoleAddr string, cmdBuilder f
 
 	conn, err := net.Dial("tcp", remoteConsoleAddr)
 	if err != nil {
-		return errors.Wrap(err, "failed to connect to remote debugger")
+		// If the IP we derived at start fails, try the reserved gateway address for our internal CNI network.
+		// The CIDR range for this can be found in buildkitd/cni-conf.json.template, so if that ever changes, we need to change it here, too.
+		// Relevant CNI docs for the host-local ipam module: https://www.cni.dev/plugins/current/ipam/host-local/
+		// tl;dr we can assume the gateway is at .1 in the subnet.
+		log.Debug(fmt.Sprintf("Failed to connect to \"%s\", trying internal CNI fallback \"%s\".", remoteConsoleAddr, cniFallbackHost))
```
Comment (alexcb) [inline cmd/debugger/main.go:98]: The rest of the logging in the debugger all uses lowercase.
```suggestion
		log.Debug(fmt.Sprintf("failed to connect to %q", trying internal CNI fallback \"%s\".", remoteConsoleAddr, cniFallbackHost))
```

**Review by alexcb — APPROVED** [review]
looks good, just a minor nit.

File: cmd/debugger/main.go (hunk 1 above)
Comment (dchw) [reply cmd/debugger/main.go:102]: We could. I was just trying to preserve the old behavior first. Ill do that now.

Comment (dchw) [reply cmd/debugger/main.go:102]: Done.

File: cmd/debugger/main.go [hunk 3]
```diff
@@ -87,9 +89,17 @@ func populateShellHistory(cmd string) error {
...
 	log := slog.GetLogger(ctx)
 
-	conn, err := net.Dial("tcp", remoteConsoleAddr)
+	conn, err := net.Dial("tcp", cniGateway)
 	if err != nil {
-		return errors.Wrap(err, "failed to connect to remote debugger")
+		// If the IP we derived at start fails, try the reserved gateway address for our internal CNI network.
+		// The CIDR range for this can be found in buildkitd/cni-conf.json.template, so if that ever changes, we need to change it here, too.
+		// Relevant CNI docs for the host-local ipam module: https://www.cni.dev/plugins/current/ipam/host-local/
+		// tl;dr we can assume the gateway is at .1 in the subnet.
```
Comment (vladaionescu) [inline cmd/debugger/main.go:97]: This comment needs to be tweaked as a result.

**Review by vladaionescu — APPROVED** [review]

File: cmd/debugger/main.go (hunk 3 above)
Comment (dchw) [reply cmd/debugger/main.go]: Moved it to be next to the CNI connection attempt.

**Review by vladaionescu — APPROVED** [review]
