### PR TITLE
variables: support builtins in --arg-scope-and-set

### LINKED ISSUE #2879: Builtin args not set when using `--arg-scope-and-set`
For example, change https://github.com/earthly/earthly/blob/6810b288a36d0b9853cdad293a4d85e195373970/tests/builtin-args.earth to use `VERSION --arg-scope-and-set 0.7` and the build will fail.

```text
  +builtin-args-test | --> RUN test "$EARTHLY_TARGET" == "+builtin-args-test"
  +builtin-args-test | ERROR Earthfile line 21:4
  +builtin-args-test |       The command
  +builtin-args-test |           RUN test "$EARTHLY_TARGET" == "+builtin-args-test"
  +builtin-args-test |       did not complete successfully. Exit code 1

============================= ❌ FAILURE [Build 🔧] ==============================
```

### PR DESCRIPTION
**Pull request by nelsam**
This also includes a very rudimentary first pass at unit tests for `variables.Collection`.

Resolves #2879

### CODE REVIEW

File: variables/collection_test.go [hunk 1]
```diff
@@ -0,0 +1,107 @@
...
+				},
+				Features: tc.features,
+			})
+			return tc
+		})
+
+		registerBaseSpecs(o)
+
+		o.Spec("non-ARG variables ignore builtin values", func(tc testCtx) {
+			// TODO: is this what we want? non-ARG variables are required to
```
Comment (alexcb) [inline variables/collection_test.go:93]: I think that's good; otherwise a user might be tempted to do something like:

```
LET EARTHLY_TARGET
SET EARTHLY_TARGET="this-shouldnt-work"
``

File: tests/builtin-args-scope.earth
Comment (alexcb) [inline tests/builtin-args-scope.earth:1]: NIT: any chance we can use `sed` instead, e.g. https://github.com/earthly/earthly/blob/main/tests/shell-out/Earthfile#L38-L41 ? That'll reduce the chance of this file drifting from the existing tests/builtin-args.earth

**Review by alexcb — APPROVED** [review]
looks good once TODO comment is reworded.

File: variables/collection_test.go (hunk 1 above)
Comment (nelsam) [reply variables/collection_test.go:93]: Thanks! I'm glad I wrote that `TODO`, I had forgotten that was a question I had  :sweat_smile:

File: tests/builtin-args-scope.earth
Comment (nelsam) [reply tests/builtin-args-scope.earth:1]: It always feels weird to sed-replace a test like this. But your resoning makes sense. I just hope we remember to delete it when `--arg-scope-and-set` becomes the default (in `0.8`?)
