### PR TITLE
fix: SAVE IMAGE --push flag was ignored

### LINKED ISSUE #2923: --push cmd line argument tries to push SAVE IMAGE step not marked with --push flag
Hi. I am using the most recent earthly v0.7.4

Consider the following minimal `Earthfile`:

```earthfile
VERSION 0.7
FROM alpine
WORKDIR /workdir

build:
    RUN echo hello > file.txt
    SAVE IMAGE hello:latest
```

The `earthly --push +build` will fail with the following error(even though `--push` IMO should not make any difference for `+build` target):

```
              output | [          ]   0% pushing layers
             ongoing | output (5 seconds ago)
              output | [----------] 100% pushing layers
              output | WARN: The command 'exporting outputs' failed: server message: insufficient_scope: authorization failed
             ongoing | Waiting on Buildkit... (Utilization: unknown other builds, 0/20 op load)
Share your logs with an Earthly account (experimental)! Register for one at https://ci.earthly.dev.
Error: build target: build main: failed to run Build function: failed to SAVE IMAGE: server message: insufficient_scope: authorization failed
```

The error says that the push failed. Earthly just tried to push `hello:latest` to dockerhub. If I prefix `hello:latest` with my dockerhub username, the push will succeed.

---

The reason why I assume the `--push` cmd line argument should not make any effect in this case, is because based on the [`earthly` cmd line reference](https://docs.earthly.dev/v/earthly-0.7/docs/earthly-command#earthly):

> `--push` ... Instructs Earthly to push __any docker images declared with the `--push`__ flag to remote docker registries and to run any `RUN --push` commands.

But my `SAVE IMAGE` step is not marked with `--push` flag.

The [`SAVE IMAGE` reference](https://docs.earthly.dev/v/earthly-0.6/docs/earthfile#save-image) also confirms my assumption:

> __The `--push` options marks the image to be pushed to an external registry__ after it has been loaded within the docker daemon available on the host.
> ... __The actual push is not executed by default. Add the `--push` flag to the earthly invocation to enable pushing.__

### PR DESCRIPTION
**Pull request by alexcb**
An image should only be pushed when the `SAVE IMAGE --push ...` command is used in combination with earthly being run with the --push flag on the cli; this fixes a regression where simply running `earthly --push` would cause all `SAVE IMAGE ...` commands to be pushed regardless of if the command had a `--push` or not.

Fixes #2923

### CODE REVIEW

File: earthfile2llb/converter.go [hunk 1]
```diff
@@ -1098,7 +1098,7 @@ func (c *Converter) SaveImage(ctx context.Context, imageNames []string, pushImag
 			c.mts.Final.SaveImages = append(c.mts.Final.SaveImages, si)
 		}
 
-		if pushImages && imageName != "" && c.opt.UseInlineCache {
+		if hasPushFlag && imageName != "" && c.opt.UseInlineCache {
```
Comment (vladaionescu) [inline earthfile2llb/converter.go:1101]: These are just renames in this file, right?

File: earthfile2llb/save_image_wait_item.go [hunk 2]
```diff
@@ -38,6 +39,6 @@ func (siwi *saveImageWaitItem) SetDoPush() {
 	siwi.mu.Lock()
 	defer siwi.mu.Unlock()
 	if siwi.si.DockerTag != "" {
-		siwi.push = true
+		siwi.doPush = siwi.allowPush
```
Comment (vladaionescu) [inline earthfile2llb/save_image_wait_item.go:42]: This is the key change, right?

**Review by vladaionescu — APPROVED** [review]

File: earthfile2llb/converter.go (hunk 1 above)
Comment (alexcb) [reply earthfile2llb/converter.go:1101]: correct -- just renaming the function arg to make it more clear that it represents a `SAVE IMAGE` vs `SAVE IMAGE --push`.

File: earthfile2llb/save_image_wait_item.go (hunk 2 above)
Comment (alexcb) [reply earthfile2llb/save_image_wait_item.go:42]: good eyes! yeah we were always setting it to `true` whenever a `SAVE IMAGE` was chained via a `BUILD`, and forgot if the `SAVE IMAGE` had a `hasPushFlag=true`.
