### PR TITLE
fix: BUILD --auto-skip saving hashes from failures

### LINKED ISSUE #4054: `BUILD --auto-skip` is caching failures
### What went wrong?

```Earthfile
VERSION --build-auto-skip 0.8

foo:
  FROM alpine
  RUN false

test:
  BUILD --auto-skip +foo
```

on the first run, it fails:

```
earthly --auto-skip-db-path=test.db --auto-skip +test
 Init 🚀
————————————————————————————————————————————————————————————————————————————————

           buildkitd | Found buildkit daemon as docker container (earthly-buildkitd)

Streaming logs to https://cloud.earthly.dev/builds/5a406978-9c0a-4251-a98e-a6f70feec269

 Build 🔧
————————————————————————————————————————————————————————————————————————————————

              logbus | Setting organization "" and project ""
               +test | --> FROM +base
               +test | --> BUILD +foo
                +foo | --> FROM +base
              alpine | --> Load metadata alpine linux/amd64
                +foo | --> FROM alpine
                +foo | [----------] 100% FROM alpine
                +foo | --> RUN false
                +foo | ERROR Earthfile line 5:2
                +foo |       The command
                +foo |           RUN false
                +foo |       did not complete successfully. Exit code 1

================================== ❌ FAILURE ===================================

                +foo *failed* | Repeating the failure error...
                +foo *failed* | --> RUN false
                +foo *failed* | [no output]
                +foo *failed* | ERROR Earthfile line 5:2
                +foo *failed* |       The command
                +foo *failed* |           RUN false
                +foo *failed* |       did not complete successfully. Exit code 1
```

however on the **second** run auto-skip is activated:

```
$ earthly --auto-skip-db-path=test.db --auto-skip +test
 Init 🚀
————————————————————————————————————————————————————————————————————————————————

           buildkitd | Found buildkit daemon as docker container (earthly-buildkitd)

Streaming logs to https://cloud.earthly.dev/builds/c1ea9f00-dcac-4906-a3da-a76eeeca2b51

 Build 🔧
————————————————————————————————————————————————————————————————————————————————

              logbus | Setting organization "" and project ""
               +test | --> FROM +base
           auto-skip | Target +foo (hash 41aa6c9fb9b83fa2461fb4c99a6ad612dd652c63) has already been run. Skipping.
skipping builder.go bf code due to GlobalWaitBlockFtr
              output | --> exporting outputs

 Push Summary ⏫ (disabled)
————————————————————————————————————————————————————————————————————————————————

To enable pushing use earthly --push

 Local Output Summary 🎁
————————————————————————————————————————————————————————————————————————————————
```

### What should have happened?

the first run failed, therefore no auto-skip entry should have been recorded.

the second run should not invoke auto-skip, and it should re-run the same step that failed.

### What earthly version?

earthly version prerelease 1b3bfd421ad54c04ece9134bc822dc6dc3b5fc1d linux/amd64; Ubuntu 23.10 (Mantic Minotaur)

### Buildkit Logs

_No response_

### Other Helpful Information

_No response_

### PR DESCRIPTION
**Pull request by alexcb**
fixes #4054

### CODE REVIEW

File: earthfile2llb/converter.go [hunk 1]
```diff
@@ -1949,6 +1952,7 @@ func (c *Converter) checkAutoSkip(ctx context.Context, fullTargetName string, al
 	}
 
 	return exists, func() {
+		fmt.Printf("Adding auto-skip %s\n", targetHash)
```
Comment (vladaionescu) [inline earthfile2llb/converter.go:1955]: Forgotten debug message?

**Review by vladaionescu — APPROVED** [review]

File: earthfile2llb/converter.go (hunk 1 above)
Comment (alexcb) [reply earthfile2llb/converter.go:1955]: good catch :)
