### PR TITLE
fix: support saving large files on failure

### LINKED ISSUE #2452: Artifact saving in FINALLY is buggy
I want to save a test report even on failure, so I'm trying to use `--try` from #587. If the artifact is not tiny, I see it getting cropped somehow! Check it out:

```
VERSION --try 0.6
FROM mambaorg/micromamba:jammy

works:
  RUN head -c 500k < /dev/zero > hello
  RUN ls -l hello
  TRY
    RUN true
  FINALLY
    SAVE ARTIFACT hello AS LOCAL hello
  END

buggy:
  RUN head -c 500k < /dev/zero > hello
  RUN ls -l hello
  TRY
    RUN false
  FINALLY
    SAVE ARTIFACT hello AS LOCAL hello
  END
```

Output:

```
$ rm -f hello; earthly --no-cache +works; ls -l hello
              +works | --> RUN head -c 500k < /dev/zero > hello
              +works | --> RUN ls -l hello
              +works | -rw-r--r-- 1 mambauser mambauser 512000 Nov 25 20:49 hello
              +works | --> RUN true
              +works | --> SAVE ARTIFACT hello +works/hello AS LOCAL hello
              output | --> exporting outputs
========================== 🌍 Earthly Build  ✅ SUCCESS ==========================
-rw-r--r-- 1 darabos darabos 512000 Apr 16  2020 hello
```

```
$ rm -f hello; earthly --no-cache +buggy; ls -l hello
              +buggy | --> RUN head -c 500k < /dev/zero > hello
              +buggy | --> RUN ls -l hello
              +buggy | -rw-r--r-- 1 mambauser mambauser 512000 Nov 25 20:45 hello
              +buggy | --> RUN false
              +buggy | ERROR Earthfile line 17:4
              +buggy |       The command
              +buggy |           RUN false
              +buggy |       did not complete successfully. Exit code 1
============================ ❌ FAILURE [2. Build 🔧] ============================
-rw-r--r-- 1 darabos darabos 53248 Nov 25 21:45 hello
```

It still manages to create `hello` on failure, but it's just 53,248 bytes! Where's the rest of my file?

For sizes up to 65,535 bytes it works. For sizes larger than that I get (SIZE % 65536) bytes.

Looks like an all-zero file is kind of a special case. With `head -c 500k < /dev/random` the file doesn't get created if it's longer than 65,535 bytes. And this is what I see in my real use case with an 8 MB zip file.

### PR DESCRIPTION
**Pull request by alexcb**
Fixes #2452

Signed-off-by: Alex Couture-Beil <alex@earthly.dev>

### CODE REVIEW

File: cmd/debugger/main.go [hunk 1]
```diff
@@ -21,6 +23,8 @@ import (
 	"github.com/sirupsen/logrus"
 )
 
+const uint16Max = 65535
```
Comment (alexcb) [inline cmd/debugger/main.go:26]: does this exist in an official go package? I couldn't find it anywhere.

**Review by vladaionescu — APPROVED** [review]
