### PR TITLE
Handle mixed files and subdirectories on wildcard

### LINKED ISSUE #689: SAVE ARTIFACT ./* AS LOCAL not capturing all files
## Repro steps
1. `git clone https://github.com/jazzdan/earthly-tons-of-artifacts.git`
2. `cd earthly-tons-of-artifacts`
3. `earthly +docker-setup`

## What I expected to happen
The Earthfile copies everything from `lib` in to the image (`COPY lib/* .`) then saves everything in the current working directory in to the out directory. `out` should be exactly the same as `lib` after `earthly` runs.

## What actually happens
`out` contains a subset of files from `lib`:

```
├── out
│   ├── gdkx-autocleanups.h
│   ├── gdkx11applaunchcontext.h
│   ├── gdkx11cursor.h
│   ├── gdkx11device-core.h
│   ├── gdkx11device-xi2.h
│   ├── gdkx11device.h
│   ├── gdkx11devicemanager-core.h
│   ├── gdkx11devicemanager-xi2.h
│   ├── gdkx11devicemanager.h
│   ├── gdkx11display.h
│   ├── gdkx11displaymanager.h
│   ├── gdkx11dnd.h
│   ├── gdkx11glcontext.h
│   ├── gdkx11keys.h
│   ├── gdkx11monitor.h
│   ├── gdkx11property.h
│   ├── gdkx11screen.h
│   ├── gdkx11selection.h
│   ├── gdkx11utils.h
│   ├── gdkx11visual.h
│   └── gdkx11window.h
```

### PR DESCRIPTION
**Pull request by dchw**
Resolves #689

### CODE REVIEW

File: builder/builder.go [hunk 1]
```diff
@@ -515,10 +515,10 @@ func (b *Builder) saveArtifactLocally(ctx context.Context, artifact domain.Artif
 				}
 			} else {
 				// Remove pre-existing dest dir.
-				err = os.RemoveAll(to)
-				if err != nil {
-					return errors.Wrapf(err, "rm -rf %s", to)
-				}
+				// err = os.RemoveAll(to)
```
Comment (alexcb) [inline builder/builder.go:518]: Do you suspect we'll revisit this commented out code, or can this else case be removed?

Comment (dchw) [reply builder/builder.go:518]: It can be removed. I wanted to run all the tests, etc... wasn't quite ready for a review yet :D

Comment (dchw) [reply builder/builder.go:518]: I  agree. Commented out code should be deleted, thats what source control is for :D

Comment (alexcb) [reply builder/builder.go:518]: hah, whoops, I think I just clicked on it without realising it was a draft :)

File: builder/builder.go [hunk 2]
```diff
@@ -515,10 +515,10 @@ func (b *Builder) saveArtifactLocally(ctx context.Context, artifact domain.Artif
...
+				// if err != nil {
+				// 	return errors.Wrapf(err, "rm -rf %s", to)
+				// }
```
Comment (vladaionescu) [inline builder/builder.go:521]: This doesn't look right.

The core idea is that if the artifact is a directory it should come out locally as that same directory, and not as a merged version of it+whatever already exists. Reason: If a build is being repeated and the new output no longer includes a certain file, then that file should now be removed.

**Review by vladaionescu — CHANGES_REQUESTED** [review]
It might be useful to also have an integration test here.

File: builder/builder.go (hunk 1 above)
Comment (dchw) [reply builder/builder.go:518]: Its not; I make my PR's from inside VSCode, and starting as a draft isn't an option :(

File: builder/builder.go (hunk 2 above)
Comment (dchw) [reply builder/builder.go:521]: I wasnt quite ready for a review yet :D Yall are quick right now?

I question the need for cleanup; but maybe this means that a (`--no-cleanup`/`--merge`) option would be nice. For sure there have been times I wanted that; say comingling earthly-made builds with local made builds.

Comment (dchw) [reply builder/builder.go:521]: ALso this was here just to see what the CI would think since I still havent set up locally to run tests with the new QEmu dependency

**Comment by dchw** [comment]
The integration test I added fails on older Earthly, by producing only two files. The new one includes the subdirectories.

**Review by alexcb — APPROVED** [review]
nice test :)

**Review by vladaionescu — APPROVED** [review]
Seems correct to me.
