### PR TITLE
llbutil/authprovider: add logic for looking up podman auth files

### LINKED ISSUE #3038: Earthly with Rootfull podman unable to authenticate/push to artifactory, creds are not passed?
**What went wrong?**

When i try to push images i get the following error:
```
Error: build target: build main: failed to run Build function: failed to SAVE IMAGE: unexpected status from POST request to http://artifactory.local/v2/docker-dev/earthly-test/python/blobs/uploads/: 403 Forbidden
```

I have been able to reproduce the same issue on multiple hosts, in different network contexts and OSes. Always running last earthly binary towards artifactory

```
VERSION 0.7

python:
    ARG DEBIAN_VERSION=$DEBIAN_DEFAULT_TARGET
    ARG VERSION=$PYTHON_DEFAULT_VERSION
    ARG EARTHLY_TARGET_NAME
    FROM python:$VERSION-$DEBIAN_VERSION
    ARG REGISTRY_BASE_PATH="artifactory.local/docker-dev/earthly-test"

    #IF [ $DEBIAN_VERSION = "bullseye" ]
    #    SAVE IMAGE --push $REGISTRY_BASE_PATH/$EARTHLY_TARGET_NAME:$VERSION
    #END
    SAVE IMAGE --push $REGISTRY_BASE_PATH/$EARTHLY_TARGET_NAME:$VERSION-$DEBIAN_VERSION

python-all:
    

    BUILD +python \
        --VERSION=3.8 \
        --VERSION=3.9 \
        --VERSION=3.10 \
        --VERSION=3.11 \
        --DEBIAN_VERSION=buster \
        --DEBIAN_VERSION=bullseye
        # bookworm is next, no date set yet
```

**What should have happened?**

No workaround found found thus far. If I could get a list of images outputted, I could use skopeo to do the actual pushing instead of earthly

**Other Helpful Information**

- The logs from the `earthly-buildkitd` container, usually from running `docker logs earthly-buildkitd`.

```
sudo podman logs earthly-buildkitd
starting earthly-buildkit with EARTHLY_GIT_HASH=83add94bc251b22935fb492c08cd516556f03f7c BUILDKIT_BASE_IMAGE=github.com/earthly/buildkit:697d0f450f91547768404dfdcd2f767a5e309c0f+build
detected cgroups v2; buildkit/entrypoint.sh running under pid=1
Autodetecting iptables
Detected iptables-legacy module
sh: out of range
BUILDKIT_ROOT_DIR=/tmp/earthly/buildkit
CACHE_SIZE_MB=0
BUILDKIT_MAX_PARALLELISM=20
BUILDKIT_LOCAL_REGISTRY_LISTEN_PORT=8371
EARTHLY_ADDITIONAL_BUILDKIT_CONFIG=debug = true

[registry."docker.io"]
   mirrors = ["artifactory.local"]

[registry."quay.io"]
   mirrors = ["artifactory.local"]

[registry."gcr.io"]
   mirrors = ["artifactory.local"]

[registry."artifactory.local"]
   http = true

[registry."127.0.0.1"]
   location = "127.0.0.1:8371"
   insecure = true

CNI_MTU=1500
OOM_SCORE_ADJ=0

======== CNI config ==========
{
	"cniVersion": "0.3.0",
	"name": "buildkitbuild",
	"type": "bridge",
	"bridge": "cni0",
	"isGateway": true,
	"ipMasq": true,
	"mtu": 1500,
	"ipam": {
		"type": "host-local",
		"subnet": "172.30.0.0/16",
		"routes": [
			{ "dst": "0.0.0.0/0" }
		]
	}
}
======== End CNI config ==========

======== Buildkitd config ==========
debug = false
root = "/tmp/earthly/buildkit"
insecure-entitlements = [ "security.insecure" ]

[grpc]
  address = [ "tcp://0.0.0.0:8372" ]

# Please note the required indentation to fit in buildkit.toml.template accordingly.

  [grpc.tls]
    cert = "/etc/cert.pem"
    key = "/etc/key.pem"
    ca = "/etc/ca.pem"

[worker.oci]
  enabled = true
  snapshotter = "auto"
  max-parallelism = 20
  gc = true
  networkMode = "cni"
  cniBinaryPath = "/usr/libexec/cni"
  cniConfigPath = "/etc/cni/cni-conf.json"
  
  

debug = true

[registry."docker.io"]
   mirrors = ["artifactory.local"]

[registry."quay.io"]
   mirrors = ["artifactory.local"]

[registry."gcr.io"]
   mirrors = ["artifactory.local"]

[registry."artifactory.local"]
   http = true

[registry."127.0.0.1"]
   location = "127.0.0.1:8371"
   insecure = true

======== End buildkitd config ==========

======== OOM Adjust script ==========
#! /bin/sh

set -e

OOM_ADJ="0"
DEBUG="false"
INVOCATION=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 6 ; echo '')

log() {
    ! "$DEBUG" || echo "$(date) [$INVOCATION] | $1" >> /var/log/oom_adj
}

adjust_oom() {
  echo "$1" > /proc/"$2"/oom_score_adj || true # It is ok if the OOM score fails - the PID may have exited, so it no longer matters anyways.
}

if [ "$OOM_ADJ" -eq "0" ]; then
    exit 0
fi

for PID in $(pidof buildkit-runc)
do
    PID_NAME=$(cat /proc/"$PID"/cmdline || echo "unknown")

    case "$PID_NAME" in
        # This is the POSIX way to do a string-starts-with, and accomodates the one prefix we do not want. Order here is important.
        "buildkit-runcinit"*) log "$PID was buildkit-runcinit, ignoring"; continue ;;
        "buildkit-runc"*)     log "$PID is runc parent($PID_NAME), proceeding" ;;
        *)                    log "$PID was $PID_NAME, ignoring"; continue ;;
    esac

    for CHILD_PID in $(pgrep -P "$PID")
    do
        CHILD_PID_NAME=$(cat /proc/"$CHILD_PID"/cmdline || echo "unknown")
        CHILD_OOM_ADJ=$(cat /proc/"$CHILD_PID"/oom_score_adj || echo "unknown")

        case "$CHILD_OOM_ADJ" in
            "unknown"*) log "$PID has child: $CHILD_PID($CHILD_PID_NAME), which was missing, ignoring"; continue ;;
            "0")        log "$PID has child: $CHILD_PID($CHILD_PID_NAME) with oom_score_adj: $CHILD_OOM_ADJ"; continue ;;
            *)          log "$PID has child: $CHILD_PID($CHILD_PID_NAME), oom_score_adj was set to 0: $CHILD_OOM_ADJ" ;;
        esac
        # The child may have started _after_ this script ran on the parent (or other invocation of) buildkit-runc.
        # This undoes the inherited adjustment to make sure we behave properly at OOM time.
        adjust_oom "0" "$CHILD_PID"
    done

    PID_NAME=$(cat /proc/"$PID"/cmdline || echo "unknown")
    case "$PID_NAME" in
        # Just in case the process exec-ed another program between the initial filter and now.
        "buildkit-runcinit"*) log "$PID was buildkit-runcinit, no longer a candidate for OOM adjustment, ignoring"; continue ;;
        "buildkit-runc"*)     log "$PID oom_score_adj was set to 0" ;;
        *)                    log "$PID was $PID_NAME, no longer a candidate for OOM adjustment, ignoring"; continue ;;
    esac
    adjust_oom "$OOM_ADJ" "$PID"
done
======== OOM Adjust script ==========

Detected container architecture is x86_64
time="2023-06-20T07:08:19Z" level=info msg="auto snapshotter: using overlayfs"
time="2023-06-20T07:08:19Z" level=info msg="found worker \"our2ie8tvyqdx84jtst7a4r4p\", labels=map[org.mobyproject.buildkit.worker.executor:oci org.mobyproject.buildkit.worker.hostname:c2d284fdb892 org.mobyproject.buildkit.worker.network:cni org.mobyproject.buildkit.worker.oci.process-mode:sandbox org.mobyproject.buildkit.worker.selinux.enabled:false org.mobyproject.buildkit.worker.snapshotter:overlayfs], platforms=[linux/amd64 linux/amd64/v2 linux/amd64/v3 linux/386]"
time="2023-06-20T07:08:19Z" level=warning msg="skipping containerd worker, as \"/run/containerd/containerd.sock\" does not exist"
time="2023-06-20T07:08:19Z" level=info msg="found 1 workers, default=\"our2ie8tvyqdx84jtst7a4r4p\""
time="2023-06-20T07:08:19Z" level=warning msg="currently, only the default worker can be used."
time="2023-06-20T07:08:19Z" level=info msg="Starting local registry for outputs on port 8371"
time="2023-06-20T07:08:19Z" level=warning msg="No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable." go.version=go1.20.5
time="2023-06-20T07:08:19Z" level=info msg="Starting upload purge in 5m0s" go.version=go1.20.5
time="2023-06-20T07:08:19Z" level=info msg="redis not configured" go.version=go1.20.5
time="2023-06-20T07:08:19Z" level=info msg="running server on [::]:8372"
time="2023-06-20T07:08:35Z" level=info msg="trying next host" error="failed to do request: Head \"http://artifactory.local/v2/library/python/manifests/3.8-bullseye?ns=docker.io\": context canceled" host=artifactory.local spanID=8ee7c60078e93b5d traceID=227b4f8d7b5856d1a4d9efe982c32e5d
time="2023-06-20T07:08:35Z" level=info msg="trying next host" error="failed to do request: Head \"https://registry-1.docker.io/v2/library/python/manifests/3.8-bullseye\": context canceled" host=registry-1.docker.io
time="2023-06-20T07:08:35Z" level=error msg="/moby.buildkit.v1.frontend.LLBBridge/ResolveImageConfig returned error: rpc error: code = Canceled desc = failed to do request: Head \"http://artifactory.local/v2/library/python/manifests/3.8-bullseye?ns=docker.io\": context canceled"
time="2023-06-20T07:08:35Z" level=error msg="/moby.buildkit.v1.Control/Solve returned error: rpc error: code = Canceled desc = context canceled"
time="2023-06-20T07:08:55Z" level=error msg="/moby.buildkit.v1.frontend.LLBBridge/Export returned error: rpc error: code = Unknown desc = unexpected status from POST request to http://artifactory.local/v2/docker-dev/earthly-test/python/blobs/uploads/: 403 Forbidden"
time="2023-06-20T07:09:15Z" level=error msg="/moby.buildkit.v1.Control/Solve returned error: rpc error: code = Unknown desc = failed to SAVE IMAGE: unexpected status from POST request to http://artifactory.local/v2/docker-dev/earthly-test/python/blobs/uploads/: 403 Forbidden"
time="2023-06-20T07:13:19Z" level=info msg="PurgeUploads starting: olderThan=2023-06-13 07:13:19.313922202 +0000 UTC m=-604499.743803963, actuallyDelete=true"
time="2023-06-20T07:13:19Z" level=info msg="Purge uploads finished.  Num deleted=0, num errors=1"
time="2023-06-20T07:13:19Z" level=info msg="Starting upload purge in 24h0m0s" go.version=go1.20.5
```

- The output of the failing command.
```
Error: build target: build main: failed to run Build function: failed to SAVE IMAGE: unexpected status from POST request to http://artifactory.local/v2/docker-dev/earthly-test/python/blobs/uploads/: 403 Forbidden
```

- Output of the failing command with `--verbose ` enabled, e.g. `earthly --verbose +some-failing-target`.

```
output | [----------] 100% exporting manifest sha256:fe0c54a961ee644a83f70175976b68022a470d6e3fc883e9dde5110ff748c9a4
output | [----------] 100% exporting config sha256:6159b3a57c4dfd651a7d4e1be1990d06a7288c7f843acd8469aa7d62b495d67c
output | [----------] 100% exporting manifest sha256:9a8f97757eb10c0c9c9605654113a0f2ad79b9a9c680a4ee9e48d84f9ef47aeb
output | [----------] 100% exporting config sha256:4a4b09ede6248d3e4549e47d2ba51974b95a87502a614375d065871d4a77b52e
output | [----------] 100% exporting manifest sha256:a1bf2ccbff657d93f7fab280598d2300107dc45d5cb457db476814d89aca23c9
output | [----------] 100% exporting config sha256:c0289af651f09aa76916bb8a70cf87919dc8e66c4f0b63d60f5ba159dbc59a96
output | [----------] 100% pushing layers
output | WARN: The command 'exporting outputs' failed: unexpected status from POST request to http://artifactory.local/v2/docker-dev/earthly-test/python/blobs/uploads/: 403 Forbidden

```
- When checking the bearer token with Wireshark i find the following:

```
eyJ2ZXIiOiIyIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYiLCJraWQiOiJTQnBPRlU2NGJwclYwNjl1UTJHT2g4T2VLVkt5ZS1JdVdsdFo4dnNyTGFvIn0.eyJzdWIiOiJqZi1hcnRpZmFjdG9yeUA5M2ZiZjEzYS0wNmVmLTQ5NWUtYmVmYi1hYWM2NmZmY2VmNjRcL3VzZXJzXC9hbm9ueW1vdXMiLCJzY3AiOiJhcHBsaWVkLXBlcm1pc3Npb25zXC91c2VyIiwiYXVkIjoiamYtYXJ0aWZhY3RvcnlAOTNmYmYxM2EtMDZlZi00OTVlLWJlZmItYWFjNjZmZmNlZjY0IiwiaXNzIjoiamYtYXJ0aWZhY3RvcnlAOTNmYmYxM2EtMDZlZi00OTVlLWJlZmItYWFjNjZmZmNlZjY0XC91c2Vyc1wvYW5vbnltb3VzIiwiZXhwIjoxNjg3MjUzNjc5LCJpYXQiOjE2ODcyNDQ2NzksImp0aSI6IjhjNzAzMmY0LWZkMmUtNDgzNy04MzcwLTcxNTlmZmFmNGE5MiJ9.SInmuTxXbZgacXt9RhNEI7ABjZfqFn_8OoiSsIeblXJCSoXOKks3W4zvPWIBy4wMDqidE4Day_VsfBaXhMYAtfBkXyCv3igeToBrUy3eVYbI__Xo3uGl4NOtt6vlXr-R7addbeXHYZmR5SY76sJ83ADTBsrbVgmx3q8JuRX1dXH9-ufPD7_sUnH5zbL-fjf3GOgZBHX60utJFBqdwlHOJJf8jrae-0_LEX6GW1YTVFOd26IVVEtohKjGjupRX6paqwsy_wyxxNzY71FvC5Jb3ZdcnbuCv20Xflu87UfXT2PQwAQmIjPy-wubzNXUlD5UwK35Y6hc1FhiK2k8ZxuDNw
```

```json
{
    "sub": "jf-artifactory@93fbf13a-06ef-495e-befb-aac66ffcef64/users/anonymous",
    "scp": "applied-permissions/user",
    "aud": "jf-artifactory@93fbf13a-06ef-495e-befb-aac66ffcef64",
    "iss": "jf-artifactory@93fbf13a-06ef-495e-befb-aac66ffcef64/users/anonymous",
    "exp": 1687253679,
    "iat": 1687244679,
    "jti": "8c7032f4-fd2e-4837-8370-7159ffaf4a92"
}
```

For some reason you can see the push is running without the auth from podman, the sub key should refer to my user, nikolas, but it seems like it tried without the login set with `podman login`?

### PR DESCRIPTION
**Pull request by nelsam**
Our old podman auth provider (in our buildkit fork) is very rudimentary and misses several locations that podman supports for storing its auth.json. This adds a custom auth provider that is more comprehensive, supporting both REGISTRY_AUTH_FILE and the default sudo location.

Resolves #3038

### CODE REVIEW

File: util/llbutil/authprovider/podman.go [hunk 1]
```diff
@@ -0,0 +1,138 @@
...
+}
+
+func NewPodman(stderr io.Writer, opts ...PodmanOpt) session.Attachable {
+	conf := podmanCfg{
+		os: defaultOS{},
+	}
+	for _, o := range opts {
+		conf = o(conf)
+	}
+	if authfile := conf.os.Getenv("REGISTRY_AUTH_FILE"); authfile != "" {
```
Comment (brandonSc) [inline util/llbutil/authprovider/podman.go:68]: nit: I usually find it cleaner to use os.Lookupenv since you can distinguish empty string vs not set (also I think the boolean check is a little nicer)

**Review by brandonSc — APPROVED** [review]
Looks good. I like the "fluent" style of test assertions that you've done. Don't see that as often in Go.

File: util/llbutil/authprovider/podman.go (hunk 1 above)
Comment (nelsam) [reply util/llbutil/authprovider/podman.go:68]: This code can't use the empty string, since that could cause it to read files that it shouldn't. `os.LookupEnv` can return `"", true`, so using `LookupEnv` would look like this:

```
if authfile, ok := conf.os.LookupEnv("REGISTRY_AUTH_FILE"); ok && authfile != "" {
```

Since this code needs to treat an unset variable and a variable set to the empty string the same, it's more idiomatic to use `Getenv`.
